name = "Eidomon RPG  7.31"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afdb7c99dc4e17eaf8eb73cf458954541aad3d35f9c06912f0d3109499fdf874"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
