name = "Eidomon RPG  7.31"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4af99af8b1bf258bd89d75cba14840b7618f50d35f7e4d59e48fbecd7f14f78d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
