#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			spirit = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.deeperdarker]
			echo = true
			bloom = true

		[types.wood_type.betterend]
			end_lotus = true
			jellyshroom = true
			lucernia = true
			mossy_glowshroom = true
			pythadendron = true
			dragon_tree = true
			helix_tree = true
			lacugrove = true
			tenanea = true
			umbrella_tree = true

		[types.wood_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.wood_type.legendarymonuments]
			distortion = true

		[types.leaves_type.regions_unexplored]
			bamboo = true
			golden_larch = true
			alpha = true
			apple_oak = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			spirit = true
			flowering_spirit = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.luminousworld]
			palm = true
			yellow_birch = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

		[types.leaves_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

#Disables specific entries
[entries]

		[entries.wood_type.another_furniture]
			drawer = true
			table = true
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			center_cut_log = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			edged_stripped_log = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			circle_glass_pane = true
			f_sign_stripped_log = true
			versailles_planks = true
			wise_stripped_log = true
			layered_stripped_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			planked_log = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			lumpy_stripped_log = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			suspicious_trapdoor = true
			chipped_stripped_log = true
			patient_stripped_log = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			meshed_trapdoor = true
			overgrown_log = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			k_sign_stripped_log = true
			double_herringbone_planks = true
			sign_stripped_log = true
			crated_planks = true
			horizontal_lined_glass = true
			knotted_stripped_log = true
			l_sign_stripped_log = true
			reinforced_log = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			reinforced_stripped_log = true
			slotted_trapdoor = true
			shack_door = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			stern_stripped_log = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			carved_stripped_log = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			twisted_trapdoor = true
			i_sign_stripped_log = true
			d_sign_stripped_log = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			damaged_log = true
			golden_barred_trapdoor = true
			nailed_log = true

		[entries.leaves_type.regions_unexplored]
			shrub = true
