#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Thu Nov 27 04:22:47 AEDT 2025
a=false
another_furniture=true
chipped=true
create=true
farmersdelight=true
regions_unexplored=true
