#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Nov 26 01:03:20 AEDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=ComplementaryReimagined-main.zip
