#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Nov 27 23:45:11 AEDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.6.1.zip
