[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true

			[light_sources.settings.entities.minecraft]
				chicken = true
				trader_llama = true
				cow = true
				tropical_fish = true
				pig = true
				skeleton = true
				bat = true
				area_effect_cloud = true
				armadillo = true
				zombie = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				wolf = true
				villager = true
				salmon = true
				wandering_trader = true
				tnt_minecart = true
				zombie_villager = true
				item_frame = true
				horse = true
				minecart = true
				glow_squid = true
				witch = true
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.samurai_dynasty]
				enenra = true

			[light_sources.settings.entities.luminousworld]
				bass_fish = true
				spring_azure = true
				trout_fish = true
				monarch = true
				miner_skeleton = true
				swallowtail = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				savannah_creeper = true
				bamboo_creeper = true
				dripstone_creeper = true
				jungle_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.knightquest]
				ghosty = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.cobblemon]
				pokemon = true
